### ISSUE TITLE
Some imporvements/bugs

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#2]
Hello,
First thing, by default on Elementary os the font isnt supporting the emojis..so if you can use a font by default in the app? 
![capture du 2015-01-12 01 26 31](https://cloud.githubusercontent.com/assets/7660997/5697749/3d6a37c4-99fa-11e4-82fc-f427543525a6.png)

And the second thing, the followers list have not a scrollbar so you cant see all the followers 
![capture du 2015-01-12 01 27 01](https://cloud.githubusercontent.com/assets/7660997/5697769/c9890f64-99fa-11e4-8bf2-4b8d5cf62b52.png)

And one last thing, for settings(Change Password/Manage Applications..) its not supported yet nop? because its not working 

Thank you for the great work!!

UPD: So, what's still needs to be fixed:
- implement profile settings/change passwords
- when i check the feeds then i go back to check my profil or conversely; i got this weird bug

**Comment by bilelmoussaoui** [comment]
I forget to report this one! Sometimes when i check the feeds then i go back to check my profil or conversely; i got this weird bug
![capture du 2015-01-12 01 33 44](https://cloud.githubusercontent.com/assets/7660997/5697783/1936adf0-99fb-11e4-95b9-d085d5f19f13.png)

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I know about the first one (I've seen it in a lot of applications before, not only mine) but I currently don't know how to deal with it, will look at it later.
The second one is easy, I just forgot to fix it.
The fourth one is completely strange to me.

Anyway, I'll look at it all  later today.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui forgot to mention, profile settings currently don't work, I will implement them later.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui fixed the second one

**Comment by bilelmoussaoui** [comment]
Nice! i tried it everything is fine now, just one problem, whenever you go and see you your followers for exemple, and then you go to an other profile for ex and check his followers: the scrollbar remember the position of the last time even if it was in your profile ? i dont know if you are going to understand this :s

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I think I understand what are you talking about, I faced it before. Will try to fix it little lit later.

**Comment by bilelmoussaoui** [comment]
The bug has been fixed thanks !

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui About the emojis: as I figured out, you should just install `ttf-ancient-fonts` package, and they will be displayed. There is seems to be no way to make them colored (like in Apple devices), but at least they should be displayed correctly).
I added it into dependencies to README
