### ISSUE TITLE
Nearby instagramers doesn't detect my real position 

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#3]
Hello
when i use the nearby option (on search) its detect that i'm in Japan while i live in Belguim 
![capture du 2015-01-12 21 21 09](https://cloud.githubusercontent.com/assets/7660997/5710296/3f20589e-9aa1-11e4-84f0-cf87fab81645.png)
i dont know if you have already implemented a code to detect position or not yet ? 
Thanks !

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui It's random now, because the geolocation doesn't work at the moment. I'll look into this.

**Comment by serge1peshcoff** [comment]
I made some changes that should fix it, so I'm marking this as closed. If you'll face it, open a new one (or reopen it, I don't know if you can reopen a bug on Github).
