### ISSUE TITLE
Add a message when no user/tag found 

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#4]
Hello,
i've a little request, its would be good to add a message when you look for a user/tag and you dont found anything?

![capture du 2015-01-12 21 21 42](https://cloud.githubusercontent.com/assets/7660997/5710333/8a621a86-9aa1-11e4-9fd4-01f7d8922488.png)

you might keep waiting for a long time  if nothing has been shown ! haha

**Comment by serge1peshcoff** [comment]
That's a great idea, I'll do it.

**Comment by serge1peshcoff** [comment]
I guess I've done it, try this.
If something is wrong, reopen it.
