### ISSUE TITLE
Showing the real name instead of the username?

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#5]
Hello
i would like to ask you to show the real name of the commentators? like on mobile version/web version !
![capture du 2015-01-12 21 28 17](https://cloud.githubusercontent.com/assets/7660997/5710401/121318d6-9aa2-11e4-9c57-75776bb2ff90.png)

Also; i have one more request; if you can add a button to refresh the current window? if you're looking on the notifications windows, you refresh and you get if there's anything new? as the application refresh automatically every x seconds/minutes ! so it would be cool to have this option too ! 
IDEA: you can make like on the mobile app by droping down to refresh?

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I don't think it's a good idea (though I'm complete newbie at design and UX), but I think maybe I'll do popover when hovering over username that shows user's full name.
About the second one: I didn't think about it, this is what needs to be implemented.

**Comment by bilelmoussaoui** [comment]
@serge1peshcoff I would love to fork your source code as a base for an unofficial instagram client for Gnome, of course all the credits in the files/code created by you will mention your name! What do you think about that?

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui yeah, sure, I am cool with that.
