### ISSUE TITLE
Very weird bug ! nothing is shown

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#7]
Hello, 
i tried the application on elementary os ferya 0.3 beta 1 kernel version : 3.13.0-44-generic
but nothing is going right ! the application was working fine in the few first hours and then.. 
![capture du 2015-01-14 23 03 34](https://cloud.githubusercontent.com/assets/7660997/5748634/ca4f554a-9c41-11e4-894c-cdb4fc198871.png)
i removed the cache, reinstall the application but still the same error , could you help me debug this ? or at last to add the unistall file? so the application will be completly removed so i can try to reinstall it 
again?

when i use the application from terminal i got this 
(photostream:15539): Gtk-CRITICAL **: gtk_application_get_app_menu: assertion 'GTK_IS_APPLICATION (application)' failed

(photostream:15539): Gtk-CRITICAL **: gtk_application_get_menubar: assertion 'GTK_IS_APPLICATION (application)' failed

PS : the notifications are working, even the notification window (in the app)

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui it seems the feed is loading correctly, but isn't displayed, that's strange.
I currently don't know what can cause it.
Are other windows (like "You" tab) displays the same or they all aren't displayed?
And did it stopped working after you `git pull`ed source from this repo and rebuilt it? If yes, there must be something with latest commits (I've done some structure changing in feed in the latest commits).

**Comment by bilelmoussaoui** [comment]
its happend before i rebuilt the last version :s

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui indeed, that's strange.
Could you do something (e.g. installing/removing some library) that could cause such behaviour? Because I haven't noticed it in my PC, so it has to be specific PC's problem (e.g. some libs aren't installed etc). 
And are other tabs with feed view (like "You tab") displays the same or they are displayed properly?

About uninstalling: CMake doesn't provide uninstalling feature, as I understood. So there is no possibility to remove this app (at least not before I figure out how to build deb package and upload it to repo). But you can do what I did: use `sudo checkinstall` instead of `sudo make install` which will generate the Debian package from the sources, then removing it via `dpkg -r <packagename>`.

**Comment by bilelmoussaoui** [comment]
The only thing ive done is to upgrade my system..i tried to rebuild it again but nothing works :s

**Comment by bilelmoussaoui** [comment]
I've been busy for a while, i gave it a try today; i upgraded to the last webkit2gtk (2.6.4) upgraded my system, and now i can see this 
![capture du 2015-01-17 21 06 54](https://cloud.githubusercontent.com/assets/7660997/5790174/d0575ecc-9e8c-11e4-8752-f6657ee526f1.png)
but when i click on login i see nothing? even if i'm pretty sure that everything should be working ! when i tried it with a root permission all the informations that i got its that i'm using libwebkit2gtk 2.6.4:
if you can add some error messages like if the app cannot connect ? so i can help you fix this :)
Thank you !

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui are there any error messages? or something?

**Comment by bilelmoussaoui** [comment]
Nothing at all :( i installed the last version of all the packages that i must have to build the applications , by building them from their source code...
but i've seen two weird things while building the application 
- PKG_CONFIG_PATH: ""
  -- Granite support: OFF
  Granite support is off even if i'm using Elementary Os? 

and while installing (sudo make install) i got this 
Warning in file "/usr/share/applications/pantheon-files.desktop": usage of MIME type "x-directory/gnome-default-handler" is discouraged ("x-directory" is an old media type that should be replaced with a modern equivalent)
Warning in file "/usr/share/applications/pantheon-files.desktop": usage of MIME type "x-directory/normal" is discouraged ("x-directory" is an old media type that should be replaced with a modern equivalent)

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui Granite support is enabled by installing `libgranite2` and `libgranite-dev` (I guess), try it.
And these 2 warnings seems to be not related to my app.
Anyway, these 2 dependencies are for GUI and they're not related to webkit2gtk, that's strange.

I am trying to make a repo with my app in Launchpad, currently it's not containing this app, but it should contain `libwebkit2gtk-4.0-37` and `libwebkit2gtk-4.0-dev`, try installing these from my repo: https://launchpad.net/~photostream-dev/+archive/ubuntu/daily.
If this won't work, I don't know what should work.

**Comment by bilelmoussaoui** [comment]
For Grainte Support, after installing libgranite-dev its has been detected now ! can you compare please the versions of packages if you're using elementary os too? http://pastebin.com/YWum43vK

I will try to install webkit2gtk from your ppa and tell you if everything is working or not ! Anyway thank you

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I'm using elementary OS too and the versions are the same (except webkitgtk-4.0)

**Comment by bilelmoussaoui** [comment]
Its working! Thank you !! You can close this ;)
